apiVersion: apps/v1
kind: Deployment
metadata:
  name: spread
spec:
  replicas: 4
  selector:
    matchLabels:
      app-name: spread
  template:
    metadata:
      annotations:
        hami.io/node-scheduler-policy: binpack
        hami.io/gpu-scheduler-policy: binpack
      labels:
        app-name: spread
    spec:
      containers:
        - name: main
          image: vllm/vllm-openai:latest
          command:
            - vllm
            - serve
            - Qwen/Qwen3-4B
            - --max-model-len=2048
            - --dtype=auto
          resources:
            limits:
              nvidia.com/gpu: "1"
              nvidia.com/gpucores: "30"
              nvidia.com/gpumem: "15000"
