apiVersion: apps/v1
kind: Deployment
metadata:
  name: qwen3-4b-mig
  labels:
    app: mig
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mig
  template:
    metadata:
      labels:
        app: mig
      annotations:
        nvidia.com/vgpu-mode: "mig"
    spec:
      containers:
        - image: vllm/vllm-openai:nightly-1f0d21064137f4fdc816864cf01832c26350be5a
          imagePullPolicy: IfNotPresent
          name: qwen3-4b-mig
          env:
            - name: LIBCUDA_LOG_LEVEL
              value: "2"
            - name: GPU_CORE_UTILIZATION_POLICY
              value: force
          command:
            - vllm
            - serve
            - Qwen/Qwen3-4B
            - --dtype=auto
            - --max-model-len=512
            - --enforce-eager
          resources:
            limits:
              nvidia.com/gpu: "1"
              nvidia.com/gpucores: "30"
              nvidia.com/gpumem: "10240"
---
apiVersion: v1
kind: Service
metadata:
  name: mig
spec:
  selector:
    app: mig
  ports:
    - protocol: TCP
      port: 8010
      targetPort: 8000
      name: vllm-svc
  type: ClusterIP
